# Site settings
title: "Date's Blog"
header-img: img/home-bg.jpg
email: tjjh89017@hotmail.com
description: ""
baseurl: "/"
url: "http://blog.datex.me"
twitter_username: tjjh89017
github_username:  tjjh89017

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
